TAP_DANCE_ENABLE = yes
EXTRAFLAGS += -flto
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
EXTRAKEY_ENABLE = yes
#RGB_MATRIX_SPLIT_RIGHT=yes

#VIA_ENABLE = yes
#VIAL_ENABLE = yes
LTO_ENABLE          = yes
OLED_ENABLE = no
COMBO_ENABLE        = no
